// <auto-generated />
using System;
using GigiTrucks.Services.Newsletter.Infrastructure.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GigiTrucks.Services.Newsletter.Infrastructure.DAL.EF.Migrations
{
    [DbContext(typeof(NewsletterDbContext))]
    [Migration("20240414151154_AddSubscription")]
    partial class AddSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("newsletter")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GigiTrucks.Services.Newsletter.Domain.Entities.Subscriber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Subscribers", "newsletter");
                });

            modelBuilder.Entity("GigiTrucks.Services.Newsletter.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubscriberId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberId")
                        .IsUnique();

                    b.ToTable("Subscriptions", "newsletter");
                });

            modelBuilder.Entity("GigiTrucks.Services.Newsletter.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("GigiTrucks.Services.Newsletter.Domain.Entities.Subscriber", "Subscriber")
                        .WithOne("Subscription")
                        .HasForeignKey("GigiTrucks.Services.Newsletter.Domain.Entities.Subscription", "SubscriberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("GigiTrucks.Services.Newsletter.Domain.Entities.Subscriber", b =>
                {
                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
