name: "orders-ci"

on:
  push:
    paths:
      - ".github/workflows/orders-ci.yaml"
      - "src/Services/Orders/**"
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/Services/Orders/Tests/GigiTrucks.Services.Orders.Tests.Unit/GigiTrucks.Services.Orders.Tests.Unit.csproj

      - name: Build
        run: dotnet build src/Services/Orders/Tests/GigiTrucks.Services.Orders.Tests.Unit/GigiTrucks.Services.Orders.Tests.Unit.csproj --no-restore

      - name: Test
        run: dotnet test src/Services/Orders/Tests/GigiTrucks.Services.Orders.Tests.Unit/GigiTrucks.Services.Orders.Tests.Unit.csproj --no-build    
    