name: "users-ci"

on:
  push:
    paths:
      - ".github/workflows/users-ci.yaml"
      - "src/Services/Users/**"
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/Services/Users/Tests/GigiTrucks.Services.Users.Tests.Integration/GigiTrucks.Services.Users.Tests.Integration.csproj

      - name: Build
        run: dotnet build src/Services/Users/Tests/GigiTrucks.Services.Users.Tests.Integration/GigiTrucks.Services.Users.Tests.Integration.csproj --no-restore

      - name: Test
        env:
          JWTSETTINGS__SECRET: ${{ secrets.JWTSETTINGS__SECRET }}
        run: dotnet test src/Services/Users/GigiTrucks.Services.Users.Tests.Integration/GigiTrucks.Services.Users.Tests.Integration.csproj --no-build    
    